### ISSUE TITLE
When is the expected date for data release?

### ISSUE THREAD

**Issue by JonghwanMun** [OpenGVLab/all-seeing#1]
I would really appreciate it if you could let me know the expected dataset release date.

**Comment by xiaomabufei** [comment]
+1

**Comment by ustcwhy** [comment]
+1

**Comment by liuheng0111** [comment]
+1

**Comment by shuchenweng** [comment]
+1

**Comment by Practicing7** [comment]
I would appreciate it if you could release some code for generating your datasets, or some methodology for generating it.

**Comment by Luyitas** [comment]
+1

**Comment by Weiyun1025** [comment]
Thank you for your interest in our work!

Today, we have released three subsets of AS-1B, including

1. [AS-Core](https://huggingface.co/datasets/OpenGVLab/AS-Core), the human-verified subset of AS-1B.
2. [AS-10M](https://huggingface.co/datasets/OpenGVLab/AS-V2/blob/main/as_pretrain_10m.json), the 10M subset of AS-1B, utilized for the pretraining of [ASMv2](https://huggingface.co/OpenGVLab/ASMv2).
3. [AS-100M](https://huggingface.co/datasets/OpenGVLab/AS-100M), the 100M subset of AS-1B.

For more details, please refer to our [README](https://github.com/OpenGVLab/all-seeing).

**Comment by luyao-cv** [comment]
> Collaborator


> Thank you for your interest in our work!
> 
> Today, we have released three subsets of AS-1B, including
> 
> 1. [AS-Core](https://huggingface.co/datasets/OpenGVLab/AS-Core), the human-verified subset of AS-1B.
> 2. [AS-10M](https://huggingface.co/datasets/OpenGVLab/AS-V2/blob/main/as_pretrain_10m.json), the 10M subset of AS-1B, utilized for the pretraining of [ASMv2](https://huggingface.co/OpenGVLab/ASMv2).
> 3. [AS-100M](https://huggingface.co/datasets/OpenGVLab/AS-100M), the 100M subset of AS-1B.
> 
> For more details, please refer to our [README](https://github.com/OpenGVLab/all-seeing).

请问图片怎么下载呀？

**Comment by Weiyun1025** [comment]
`AS-Core`和`AS-10M`用的是SA-1B的前64个切片的图像，`AS-100M`用的是前256个切片的图像，这些图像可以从[SA-1B](https://ai.meta.com/datasets/segment-anything/)下载
