### ISSUE TITLE
[Question]Can all-seeing-v2 handle images which the target does not exist for the grounding task?

### ISSUE THREAD

**Issue by HeliumCake** [OpenGVLab/all-seeing#11]
Reference to [grounding_eval.jsonl](https://huggingface.co/datasets/OpenGVLab/Region-Evaluation-Data/blob/main/grounding/grounding_eval.jsonl), I use the following prompt template:
```
Please provide the bounding box coordinate of the region this sentence describes: {target}
``` 
And based on  [all-seeing-v2/llava/eval/model_vqa_loader.py](https://github.com/OpenGVLab/all-seeing/blob/main/all-seeing-v2/llava/eval/model_vqa_loader.py), I made some modifications to test my dataset:
```python
    parser.add_argument("--model-path", type=str, default="OpenGVLab/ASMv2")
    parser.add_argument("--conv-mode", type=str, default="vicuna_v1")
    parser.add_argument("--temperature", type=float, default=0)
``` 
I want to ground the person holding a hose. But some of the images in my dataset have person holding hose, while others do not. However, the model cannot distinguish. Regardless of whether the person in the image holding a hose or not, it marks them with a box. Is there any way to make the model only mark the person holding the hose, and not mark anything when the target does not exist in the image?

And can the model mark multiple targets at once when there are multiple targets that meet the conditions in the image? For example, when there are multiple persons in the image and my target is "person", can the model output multiple boxes?

Thank you very much for your answers.

**Comment by Weiyun1025** [comment]
Thank you for your interest in our project.

Currently, ASMv2 is unable to handle these situations. You can enhance the model's capabilities by adding negative samples and object detection data. This will enable the model to either confirm the absence of the mentioned target in the scene or identify multiple targets simultaneously.

We will strive to release an updated version of ASMv2 that addresses these issues. Thank you for your feedback!
