### ISSUE TITLE
关于训练阶段的疑问

### ISSUE THREAD

**Issue by tayton42** [OpenGVLab/all-seeing#12]
您好！感谢您的工作！我看到两个阶段其实数据重合度很高，为什么不取消第一个阶段直接训练第二个阶段呢，是为了让模型更拟合通用理解能力的数据吗

**Comment by Weiyun1025** [comment]
第一阶段的训练是为了让模型学会理解图像的整体信息，第二阶段的训练是为了让模型学会理解图像的局部信息。

如果取消第一个阶段的话，模型在图像benchmark上的性能会有明显的下降（参考我们更新的arxiv论文第二版中的附录部分，我们补充了关于训练阶段的ablation study）
