### ISSUE TITLE
Usage of dataset Browser is quite tricky and often encountered with obvious mistake.

### ISSUE THREAD

**Issue by Yindong-Zhang** [OpenGVLab/all-seeing#2]
![图片](https://github.com/OpenGVLab/all-seeing/assets/19553754/f0f414ac-146d-4d63-9c86-6d1bf2a93238)

as seen in picture above, quite curious to learn why ???

**Comment by Weiyun1025** [comment]
Thank you for your interest in our project.

This dataset browser is an easy demo designed to support data visualization with mouse pointing and may have some bugs.

You can refer to our released data ([**AS-Core**](https://huggingface.co/datasets/OpenGVLab/AS-Core), [**AS-10M**](https://huggingface.co/datasets/OpenGVLab/AS-V2/blob/main/as_pretrain_10m.json), [**AS-100M**](https://huggingface.co/datasets/OpenGVLab/AS-100M)) for more details about our dataset.
