### ISSUE TITLE
when will CRPE benchmark be released?

### ISSUE THREAD

**Issue by Moonteresa** [OpenGVLab/all-seeing#4]
Great work!
But I find the link of CRPE Benchmark is 404 error:
https://huggingface.co/datasets/OpenGVLab/CRPE
Could you please kindly tell when this benchmark will be released?

**Comment by Weiyun1025** [comment]
Thank you for your interest in our project.

We will release the benchmark as soon as possible.

**Comment by Weiyun1025** [comment]
The benchmark is released! You can download it [here](https://huggingface.co/datasets/OpenGVLab/CRPE).
