### ISSUE TITLE
v2中box的坐标是怎么normalized的？

### ISSUE THREAD

**Issue by Baboom-l** [OpenGVLab/all-seeing#6]
如何可视化box标签

**Comment by Weiyun1025** [comment]
你好，可视化可以参考这个[脚本](https://github.com/OpenGVLab/all-seeing/blob/main/all-seeing-v2/scripts_asmv2/visualize_rec.py)

**Comment by Baboom-l** [comment]
square_pad这个信息在标注中有吗？还是默认都为true

**Comment by Weiyun1025** [comment]
v2的数据里默认都是true，有部分数据的文件名里标了 wo_square_pad 的是没有 square pad 的
